# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoviesList' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MoviesList
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  target 'MoviesListTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MoviesList-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MoviesList-tvOS

  target 'MoviesList-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
